// Pure generation/parsing logic, ported line-for-line from the shell's
// Settings.qml + HyprMon.qml so both writers emit byte-identical files.
// Nothing in here touches the system — that is api.js's job.

// ── Lua helpers ─────────────────────────────────────────────────────────────
export const luaEsc = (s) => String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
export const boolLua = (b) => (b ? "true" : "false");
export const hex6 = (c) => {
  const s = String(c).replace("#", "");
  return s.length === 8 ? s.slice(2) : s;
};

// ── displays (HyprMon.qml) ──────────────────────────────────────────────────
// A spec is the canonical description of one output:
// { desc, name, mode "WxH@Hz", x, y, scale, transform, vrr, bitdepth,
//   disabled, mirror, primary }

export function specFromMonitor(m) {
  let mode = `${m.width || 0}x${m.height || 0}@${Number(m.refreshRate || 60).toFixed(2)}`;
  if (!(m.width > 0) || !(m.height > 0)) {
    const am = m.availableModes || [];
    mode = am.length ? String(am[0]).replace(/Hz$/i, "") : "preferred";
  }
  return {
    desc: m.description || "",
    name: m.name,
    mode,
    x: m.x || 0,
    y: m.y || 0,
    scale: Math.round(Number(m.scale || 1) * 10000) / 10000,
    transform: m.transform || 0,
    vrr: !!m.vrr,
    bitdepth: String(m.currentFormat || "").indexOf("2101010") >= 0 ? 10 : 8,
    disabled: !!m.disabled,
    mirror: m.mirrorOf && m.mirrorOf !== "none" ? m.mirrorOf : "",
    primary: false
  };
}

export const matchId = (s) => (s.desc !== "" ? s.desc : s.name);
export const keyFor = (specs) => specs.map(matchId).sort().join(" || ");
export const modeRes = (mode) => String(mode).split("@")[0];
export const modeHz = (mode) => {
  const p = String(mode).split("@");
  return p.length > 1 ? parseFloat(p[1]) : 60;
};

/** Current live state as a spec list, primary carried over from the profile. */
export function snapshot(monitors, profiles) {
  const out = (monitors || []).map(specFromMonitor);
  const prof = (profiles || {})[keyFor(out)];
  if (prof) {
    for (const s of out) {
      const match = prof.find((p) => matchId(p) === matchId(s));
      if (match) s.primary = !!match.primary;
    }
  }
  if (!out.some((s) => s.primary) && out.length) out[0].primary = true;
  return out;
}

/** The argument table for hl.monitor{} — shared by live apply and monitors.lua */
export function luaArgs(s) {
  const out = s.desc !== "" ? "desc:" + s.desc : s.name;
  let L = `{ output = "${luaEsc(out)}"`;
  if (s.disabled) return L + ", disabled = true }";
  L += `, mode = "${s.mode}", position = "${s.x}x${s.y}", scale = ${s.scale}`;
  if (s.transform) L += `, transform = ${s.transform}`;
  L += `, vrr = ${s.vrr ? 1 : 0}`;
  // always explicit: omitting bitdepth would leave a live 10-bit output at 10
  L += `, bitdepth = ${s.bitdepth === 10 ? 10 : 8}`;
  if (s.mirror !== "") L += `, mirror = "${luaEsc(s.mirror)}"`;
  return L + " }";
}

export function monitorsLuaText(profiles, lastKey) {
  let s =
    "-- AUTO-GENERATED by Settings → Displays (Quickshell). Do not edit by hand.\n" +
    "-- Source of truth: ~/.config/quickshell/display-profiles.json — one profile\n" +
    "-- per connected-monitor set, keyed by the sorted output descriptions.\n" +
    "local profiles = {}\n";
  for (const key of Object.keys(profiles).sort()) {
    s += `profiles["${luaEsc(key)}"] = {\n`;
    for (const spec of profiles[key]) s += "    " + luaArgs(spec) + ",\n";
    s += "}\n";
  }
  s +=
    "\n-- Fallback: at boot the monitor list may not be populated yet, so first\n" +
    "-- assert the last-committed profile unconditionally (desc: rules only bind\n" +
    "-- to outputs that are actually present)…\n" +
    `local last = profiles["${luaEsc(lastKey)}"]\n` +
    "if last then for _, m in ipairs(last) do hl.monitor(m) end end\n" +
    "\n-- …then, when the connected set is known and a different profile matches it\n" +
    "-- (e.g. reload while undocked), let that profile win.\n" +
    "local names = {}\n" +
    "for _, m in ipairs(hl.get_monitors()) do\n" +
    "    local d = m.description\n" +
    '    if d == nil or d == "" then d = m.name end\n' +
    "    names[#names + 1] = d\n" +
    "end\n" +
    "table.sort(names)\n" +
    'local prof = profiles[table.concat(names, " || ")]\n' +
    "if prof and prof ~= last then for _, m in ipairs(prof) do hl.monitor(m) end end\n";
  return s;
}

/** Applied state must match the committed intent; "" = all good. */
export function verifyAgainst(specs, monitors) {
  const bad = [];
  for (const s of specs) {
    const m = (monitors || []).find((x) => matchId(specFromMonitor(x)) === matchId(s));
    if (!m) {
      bad.push(matchId(s) + ": not present");
      continue;
    }
    if (s.disabled) {
      if (!m.disabled) bad.push(m.name + ": should be disabled");
      continue;
    }
    if (m.disabled) {
      bad.push(m.name + ": is disabled");
      continue;
    }
    const live = specFromMonitor(m);
    if (s.mirror !== "") {
      if (live.mirror !== s.mirror) bad.push(m.name + ": mirror not active");
      continue;
    }
    if (modeRes(live.mode) !== modeRes(s.mode))
      bad.push(`${m.name}: mode is ${modeRes(live.mode)}, wanted ${modeRes(s.mode)}`);
    else if (Math.abs(modeHz(live.mode) - modeHz(s.mode)) > 0.6)
      bad.push(`${m.name}: ${modeHz(live.mode).toFixed(0)}Hz, wanted ${modeHz(s.mode).toFixed(0)}Hz`);
    if (live.x !== s.x || live.y !== s.y)
      bad.push(`${m.name}: position ${live.x},${live.y}, wanted ${s.x},${s.y}`);
    if (Math.abs(live.scale - s.scale) > 0.011)
      bad.push(`${m.name}: scale ${live.scale}, wanted ${s.scale}`);
    if (live.transform !== s.transform) bad.push(m.name + ": rotation not applied");
  }
  return bad.join(" · ");
}

/** resolution → refresh-rate map from availableModes (current mode seeded). */
export function modeMapFor(m, spec) {
  const am = m && m.availableModes ? m.availableModes.slice() : [];
  if (spec && spec.mode) am.unshift(spec.mode);
  const byRes = {};
  const resList = [];
  for (const raw of am) {
    const s = String(raw).replace(/Hz$/i, "");
    const res = s.split("@")[0];
    const hz = parseFloat(s.split("@")[1] || "60");
    if (!byRes[res]) {
      byRes[res] = [];
      resList.push(res);
    }
    if (!byRes[res].some((o) => Math.round(o.hz) === Math.round(hz)))
      byRes[res].push({ hz, mode: res + "@" + hz.toFixed(2), label: Math.round(hz) + " Hz" });
  }
  resList.sort((a, b) => {
    const pa = a.split("x"), pb = b.split("x");
    return pb[0] * pb[1] - pa[0] * pa[1];
  });
  for (const r in byRes) byRes[r].sort((a, b) => b.hz - a.hz);
  return { resList, byRes };
}

/** Logical (scaled, rotation-aware) size of a spec. */
export function specW(s) {
  const p = modeRes(s.mode).split("x");
  const w = s.transform % 2 ? p[1] : p[0];
  return Math.max(1, Math.round(w / s.scale));
}
export function specH(s) {
  const p = modeRes(s.mode).split("x");
  const h = s.transform % 2 ? p[0] : p[1];
  return Math.max(1, Math.round(h / s.scale));
}

// ── input (Keyboard & Mouse) ────────────────────────────────────────────────

export const INPUT_DEFAULTS = {
  kb_layout: "us", kb_variant: "", kb_options: "", repeat_rate: 25, repeat_delay: 600,
  numlock_by_default: false, sensitivity: 0, accel_profile: "", natural_scroll: false,
  left_handed: false, scroll_factor: 1,
  tp_natural_scroll: true, tp_tap: true, tp_dwt: true, tp_clickfinger: false,
  tp_scroll_factor: 1, tp_mbe: false, tp_drag_lock: false, tp_tap_drag: true
};

// [hyprland option under input:, our key] — order matters: the --batch reply
// blocks come back in command order.
export const INPUT_OPTIONS = [
  ["kb_layout", "kb_layout"], ["kb_variant", "kb_variant"], ["kb_options", "kb_options"],
  ["repeat_rate", "repeat_rate"], ["repeat_delay", "repeat_delay"], ["numlock_by_default", "numlock_by_default"],
  ["sensitivity", "sensitivity"], ["accel_profile", "accel_profile"], ["natural_scroll", "natural_scroll"],
  ["left_handed", "left_handed"], ["scroll_factor", "scroll_factor"],
  ["touchpad:natural_scroll", "tp_natural_scroll"], ["touchpad:tap-to-click", "tp_tap"],
  ["touchpad:disable_while_typing", "tp_dwt"], ["touchpad:clickfinger_behavior", "tp_clickfinger"],
  ["touchpad:scroll_factor", "tp_scroll_factor"], ["touchpad:middle_button_emulation", "tp_mbe"],
  ["touchpad:drag_lock", "tp_drag_lock"], ["touchpad:tap-and-drag", "tp_tap_drag"]
];

export function parseInputBlocks(text, current) {
  const blocks = String(text).split(/\n\s*\n/).filter((b) => b.trim() !== "");
  const p = { ...current };
  for (let i = 0; i < blocks.length && i < INPUT_OPTIONS.length; i++) {
    const m = blocks[i].split("\n")[0].match(/^(int|float|bool|str):\s?(.*)$/);
    if (!m) continue;
    let v;
    if (m[1] === "int") v = parseInt(m[2]);
    else if (m[1] === "float") v = parseFloat(m[2]);
    else if (m[1] === "bool") {
      const b = m[2].trim();
      v = b === "true" || b === "1";
    } else {
      v = m[2];
      if (v === "[[EMPTY]]") v = "";
    }
    if (v !== undefined && !(typeof v === "number" && isNaN(v))) p[INPUT_OPTIONS[i][1]] = v;
  }
  return p;
}

export function inputLua(p) {
  return (
    `hl.config({ input = { kb_layout = "${luaEsc(p.kb_layout)}", kb_variant = "${luaEsc(p.kb_variant)}", kb_options = "${luaEsc(p.kb_options)}"` +
    `, repeat_rate = ${p.repeat_rate}, repeat_delay = ${p.repeat_delay}` +
    `, numlock_by_default = ${boolLua(p.numlock_by_default)}` +
    `, sensitivity = ${p.sensitivity}` +
    (p.accel_profile !== "" ? `, accel_profile = "${luaEsc(p.accel_profile)}"` : "") +
    `, natural_scroll = ${boolLua(p.natural_scroll)}, left_handed = ${boolLua(p.left_handed)}` +
    `, scroll_factor = ${p.scroll_factor}` +
    `, touchpad = { natural_scroll = ${boolLua(p.tp_natural_scroll)}, tap_to_click = ${boolLua(p.tp_tap)}` +
    `, disable_while_typing = ${boolLua(p.tp_dwt)}, clickfinger_behavior = ${boolLua(p.tp_clickfinger)}` +
    `, scroll_factor = ${p.tp_scroll_factor}, middle_button_emulation = ${boolLua(p.tp_mbe)}` +
    `, drag_lock = ${boolLua(p.tp_drag_lock)}, tap_and_drag = ${boolLua(p.tp_tap_drag)} } } })`
  );
}

export function deviceLua(name, o) {
  let L = `hl.device({ name = "${luaEsc(name)}"`;
  if (o.sensitivity !== undefined) L += `, sensitivity = ${o.sensitivity}`;
  if (o.natural_scroll !== undefined) L += `, natural_scroll = ${boolLua(o.natural_scroll)}`;
  if (o.left_handed !== undefined) L += `, left_handed = ${boolLua(o.left_handed)}`;
  if (o.accel_profile !== undefined && o.accel_profile !== "")
    L += `, accel_profile = "${luaEsc(o.accel_profile)}"`;
  return L + " })";
}

export function inputLuaText(inp, devOverrides) {
  let s = "-- AUTO-GENERATED by Settings → Keyboard & Mouse. Do not edit by hand.\n" + inputLua(inp) + "\n";
  for (const d of Object.keys(devOverrides || {}).sort()) s += deviceLua(d, devOverrides[d]) + "\n";
  return s;
}

export const isTouchpadName = (n) => /touchpad|glidepoint|bcm5974|trackpad/i.test(n);

// Curated per-layout XKB variants (Default = no variant).
export const KB_VARIANTS = {
  us: ["", "intl", "dvorak", "colemak", "mac"], gb: ["", "extd", "intl", "dvorak", "mac"],
  ge: ["", "qwerty", "mess", "ru"], ru: ["", "phonetic", "typewriter", "mac"], ua: ["", "phonetic", "typewriter"],
  de: ["", "nodeadkeys", "neo", "mac"], at: ["", "nodeadkeys"], ch: ["", "de_nodeadkeys", "fr"],
  fr: ["", "bepo", "oss", "mac"], be: ["", "oss"], ca: ["", "fr", "multix", "eng"],
  es: ["", "nodeadkeys", "winkeys", "mac"], latam: ["", "nodeadkeys"],
  it: ["", "nodeadkeys", "mac"], pt: ["", "nodeadkeys", "mac"], br: ["", "nodeadkeys", "thinkpad"],
  nl: ["", "mac"], tr: ["", "f", "alt"], gr: ["", "polytonic", "extended"],
  pl: ["", "qwertz", "dvorak"], cz: ["", "qwerty", "qwerty_bksl"], sk: ["", "qwerty"],
  hu: ["", "standard", "nodeadkeys"], ro: ["", "std"], bg: ["", "phonetic", "bas_phonetic"],
  se: ["", "nodeadkeys", "dvorak", "mac"], no: ["", "nodeadkeys", "dvorak", "mac"], fi: ["", "nodeadkeys", "mac"],
  dk: ["", "nodeadkeys", "mac"], is: ["", "mac"],
  lt: ["", "std"], lv: ["", "apostrophe"], ee: ["", "nodeadkeys"],
  rs: ["", "latin", "yz"], hr: ["", "unicode"], si: [""],
  by: ["", "latin"], kz: ["", "latin"], am: ["", "phonetic"], az: ["", "cyrillic"],
  il: ["", "phonetic", "biblical"], ara: ["", "azerty", "qwerty"], ir: ["", "pes_keypad"],
  in: ["", "eng", "tam", "ben"], jp: ["", "kana", "mac"], kr: ["", "kr104"], cn: ["", "altgr-pinyin"],
  th: ["", "pat"], vn: [""]
};

// XKB group-toggle shortcut presets (kb_options grp:*). Super+Space is the
// DE's own Hyprland bind and always works in addition.
export const GRP_OPTIONS = [
  { label: "Super+Space only (DE bind)", value: "" },
  { label: "Alt+Shift", value: "grp:alt_shift_toggle" },
  { label: "Ctrl+Alt", value: "grp:ctrl_alt_toggle" },
  { label: "Ctrl+Shift", value: "grp:ctrl_shift_toggle" },
  { label: "Win+Space", value: "grp:win_space_toggle" },
  { label: "Caps Lock", value: "grp:caps_toggle" }
];

export const KB_PRESETS = [
  { c: "us", n: "English (US)" }, { c: "gb", n: "English (UK)" },
  { c: "ge", n: "Georgian" }, { c: "ru", n: "Russian" }, { c: "ua", n: "Ukrainian" },
  { c: "de", n: "German" }, { c: "at", n: "German (Austria)" }, { c: "ch", n: "Swiss" },
  { c: "fr", n: "French" }, { c: "be", n: "Belgian" }, { c: "ca", n: "French (Canada)" },
  { c: "es", n: "Spanish" }, { c: "latam", n: "Spanish (Latin America)" },
  { c: "it", n: "Italian" }, { c: "pt", n: "Portuguese" }, { c: "br", n: "Portuguese (Brazil)" },
  { c: "nl", n: "Dutch" }, { c: "tr", n: "Turkish" }, { c: "gr", n: "Greek" },
  { c: "pl", n: "Polish" }, { c: "cz", n: "Czech" }, { c: "sk", n: "Slovak" },
  { c: "hu", n: "Hungarian" }, { c: "ro", n: "Romanian" }, { c: "bg", n: "Bulgarian" },
  { c: "se", n: "Swedish" }, { c: "no", n: "Norwegian" }, { c: "fi", n: "Finnish" },
  { c: "dk", n: "Danish" }, { c: "is", n: "Icelandic" },
  { c: "lt", n: "Lithuanian" }, { c: "lv", n: "Latvian" }, { c: "ee", n: "Estonian" },
  { c: "rs", n: "Serbian" }, { c: "hr", n: "Croatian" }, { c: "si", n: "Slovenian" },
  { c: "by", n: "Belarusian" }, { c: "kz", n: "Kazakh" }, { c: "am", n: "Armenian" },
  { c: "az", n: "Azerbaijani" }, { c: "il", n: "Hebrew" }, { c: "ara", n: "Arabic" },
  { c: "ir", n: "Persian" }, { c: "in", n: "Indian" }, { c: "jp", n: "Japanese" },
  { c: "kr", n: "Korean" }, { c: "cn", n: "Chinese" }, { c: "th", n: "Thai" },
  { c: "vn", n: "Vietnamese" }
];

export function kbActiveList(inp) {
  const codes = String(inp.kb_layout).split(",").map((s) => s.trim()).filter((x) => x !== "");
  const vars = String(inp.kb_variant).split(",");
  return codes.map((c, i) => ({ code: c, variant: (vars[i] || "").trim() }));
}

// ── wallpapers.conf ─────────────────────────────────────────────────────────

export const isVideo = (p) => /\.(mp4|webm|mkv|mov|avi|m4v)$/i.test(p);
export const isGif = (p) => /\.gif$/i.test(p);

export function parseWallpapersConf(text) {
  const map = {};
  let mode = "fill";
  let mute = true;
  for (const l of String(text).split("\n")) {
    if (l === "" || l[0] === "#") continue;
    const k = l.indexOf("=");
    if (k <= 0) continue;
    const key = l.slice(0, k);
    const val = l.slice(k + 1);
    if (key === "mode") mode = val;
    else if (key === "mute") mute = val === "1";
    else if (key === "backend") continue; // power-user override, script-side only
    else if (val !== "") map[key] = val;
  }
  return { map, mode, mute };
}

export function wallpapersConfText(mode, mute, map) {
  let s = `# AUTO-GENERATED by Settings → Wallpaper. Do not edit by hand.\nmode=${mode}\nmute=${mute ? "1" : "0"}\n`;
  for (const k of Object.keys(map).sort()) s += `${k}=${map[k]}\n`;
  return s;
}

// ── user.lua (layout / theme overrides) ─────────────────────────────────────

export const ANIM_BASE = [
  { leaf: "global", s: 9, bz: "easeOutQuint" },
  { leaf: "border", s: 5.39, bz: "easeOutQuint" },
  { leaf: "windows", s: 5, spring: "easy", style: "popin 88%" },
  { leaf: "windowsOut", s: 3, bz: "linear", style: "popin 88%" },
  { leaf: "fade", s: 3.5, bz: "quick" },
  { leaf: "layers", s: 4, bz: "easeOutQuint", style: "fade" },
  { leaf: "workspaces", s: 5, bz: "easeOutQuint", style: "slide" }
];

export function animLuaLines(m) {
  const L = [];
  if (m <= 0) {
    L.push("hl.config({ animations = { enabled = false } })");
    return L;
  }
  L.push("hl.config({ animations = { enabled = true } })");
  for (const a of ANIM_BASE) {
    const sp = (a.s / m).toFixed(2);
    let s = `hl.animation({ leaf = "${a.leaf}", enabled = true, speed = ${sp}`;
    if (a.spring) s += `, spring = "${a.spring}"`;
    if (a.bz) s += `, bezier = "${a.bz}"`;
    if (a.style) s += `, style = "${a.style}"`;
    L.push(s + " })");
  }
  return L;
}

export function transparencyLua(windowTransparency) {
  return (
    "hl.config({ decoration = { active_opacity = 1.0, inactive_opacity = " +
    (windowTransparency ? "0.97" : "1.0") +
    " } })"
  );
}

export function tilingLua(tilingEnabled) {
  return tilingEnabled
    ? ""
    : 'hl.window_rule({ name = "float-all", match = { class = ".*" }, float = true })\n';
}

/** The full generated/user.lua, matching Settings.qml's writeOverrides(). */
export function userLuaText(o) {
  let s = "-- AUTO-GENERATED by the Quickshell Settings app. Do not edit by hand.\n";
  let gen = `hl.config({ general = { gaps_in = ${o.gapsIn}, gaps_out = ${o.gapsOut}, border_size = ${o.borderSize}`;
  if (o.tintBorders) gen += `, col = { active_border = "rgba(${hex6(o.accent)}ff)" }`;
  gen += " } })\n";
  s += gen;
  s += `hl.config({ decoration = { rounding = ${o.rounding} } })\n`;
  s += transparencyLua(o.windowTransparency) + "\n";
  const m = Number(o.animationSpeed);
  s += Math.abs(m - 1) < 0.001 ? "" : animLuaLines(m).join("\n") + "\n";
  s += tilingLua(o.tilingEnabled);
  return s;
}

// ── hypridle.conf (Screensaver pane) ────────────────────────────────────────

/**
 * saver: { enabled, min, style, lock, lockAfterMin } · lowPower shortens every
 * stage. Mirrors Settings.qml's writeIdleConf() exactly.
 */
export function hypridleConfText(saver, lowPower) {
  const idleScale = lowPower ? 0.5 : 1.0;
  const graceSec = lowPower ? 10 : 20;
  const idleAt = (sec) => Math.max(30, Math.round(sec * idleScale));
  const lockCmd = "qs ipc call lock lock";
  const undim = "qs ipc call saver undim";
  let s =
    "# AUTO-GENERATED by the Quickshell Settings app (Screensaver pane). Do not edit by hand.\n" +
    `# Timeline is ${lowPower ? "BATTERY (shortened)" : "AC"}.\n` +
    "general {\n" +
    `    lock_cmd         = ${lockCmd}\n` +
    `    before_sleep_cmd = ${lockCmd}\n` +
    "    after_sleep_cmd  = hyprctl dispatch 'hl.dsp.dpms(\"on\")'\n" +
    "    ignore_dbus_inhibit = false\n" +
    "}\n";
  const saverSec = idleAt(Math.max(60, Math.round(saver.min * 60)));
  const firstSec = saver.enabled ? saverSec : idleAt(300);
  const dimSec = Math.max(20, firstSec - graceSec);
  s += `listener {\n    timeout    = ${dimSec}\n    on-timeout = qs ipc call saver dim\n    on-resume  = ${undim}\n}\n`;
  if (saver.enabled && !saver.lock) {
    s += `listener {\n    timeout    = ${saverSec}\n    on-timeout = qs ipc call saver show\n    on-resume  = qs ipc call saver hide\n}\n`;
    if (saver.lockAfterMin > 0)
      s += `listener {\n    timeout    = ${saverSec + idleAt(saver.lockAfterMin * 60)}\n    on-timeout = ${lockCmd}\n    on-resume  = ${undim}\n}\n`;
  } else if (saver.enabled && saver.lock) {
    s += `listener {\n    timeout    = ${saverSec}\n    on-timeout = ${lockCmd}\n    on-resume  = ${undim}\n}\n`;
  } else {
    s += `listener {\n    timeout    = ${idleAt(300)}\n    on-timeout = ${lockCmd}\n    on-resume  = ${undim}\n}\n`;
  }
  // Deliberately NOT battery-shortened (matches Settings.qml): suspend is the
  // one stage the user walks into blind — a fixed, documented 15 min instead
  // of a surprise 7.5.
  s += `listener {\n    timeout    = 900\n    on-timeout = ~/.config/hypr/scripts/idle-suspend.sh\n}\n`;
  return s;
}

/** Human description of the timeline the generator above produces. */
export function idlePolicyText(saver, lowPower) {
  const idleScale = lowPower ? 0.5 : 1.0;
  const mins = (m) => Math.max(0.5, Math.round(m * idleScale * 10) / 10);
  const parts = [];
  if (saver.enabled && !saver.lock) {
    parts.push(`screensaver at ${mins(saver.min)} min`);
    parts.push(saver.lockAfterMin > 0 ? `lock at ${mins(saver.min + saver.lockAfterMin)} min` : "no auto-lock");
  } else if (saver.enabled) {
    parts.push(`lock at ${mins(saver.min)} min`);
  } else {
    parts.push(`lock at ${mins(5)} min`);
  }
  parts.push("suspend at 15 min on battery");
  parts.push("no display power-off");
  return parts.join(" · ") + (lowPower ? "   (battery timeline)" : "");
}

// ── shortcuts (SHORTCUTS.md renderer) ───────────────────────────────────────

export function shortcutsModel(md) {
  const out = [];
  for (const raw of String(md).split("\n")) {
    const t = raw.trim();
    if (t.startsWith("## ")) out.push({ h: true, a: t.slice(3), b: "" });
    else if (t.startsWith("|") && t.indexOf("---") < 0) {
      const cells = t.split("|").map((x) => x.trim()).filter((x) => x !== "");
      if (cells.length >= 2 && cells[0].toLowerCase() !== "shortcut")
        out.push({ h: false, a: cells[0].replace(/`/g, ""), b: cells[1].replace(/\*\*/g, "").replace(/`/g, "") });
    }
  }
  return out;
}

// ── misc shared data ────────────────────────────────────────────────────────

export const ACCENTS = [
  { name: "Blue", hex: "#0a84ff" }, { name: "Indigo", hex: "#5e5ce6" }, { name: "Purple", hex: "#bf5af2" },
  { name: "Pink", hex: "#ff375f" }, { name: "Red", hex: "#ff453a" }, { name: "Orange", hex: "#ff9f0a" },
  { name: "Yellow", hex: "#ffd60a" }, { name: "Green", hex: "#30d158" }, { name: "Teal", hex: "#40c8e0" },
  { name: "Graphite", hex: "#8e8e93" }
];

export const APP_CATS = [
  { key: "Browser", mime: "x-scheme-handler/https", mimes: ["x-scheme-handler/https", "x-scheme-handler/http", "text/html"] },
  { key: "Mail", mime: "x-scheme-handler/mailto", mimes: ["x-scheme-handler/mailto"] },
  { key: "Text Editor", mime: "text/plain", mimes: ["text/plain"] },
  { key: "Image Viewer", mime: "image/png", mimes: ["image/png", "image/jpeg", "image/gif", "image/webp"] },
  { key: "Video Player", mime: "video/mp4", mimes: ["video/mp4", "video/x-matroska", "video/webm"] },
  { key: "File Manager", mime: "inode/directory", mimes: ["inode/directory"] }
];

/** Desktop-entry Exec strings carry %-field codes (%U, %f…) — strip for sh -c. */
export const cleanExec = (s) => String(s || "").replace(/%[a-zA-Z]/g, "").trim();

// ── window rules (Settings → Window Rules; standalone app only) ─────────────
// Per-app open rules: send to a workspace and/or force float/tile. Matching is
// by window class (the Wayland app-id — usually the desktop-file id; X11/
// Electron apps advertise theirs via StartupWMClass). The class is regex-
// escaped and anchored so "zen" can never also catch "zen-beta". Rules are
// NAMED, which makes a `hyprctl reload` after every save idempotent — the
// reloaded config re-declares the same names instead of stacking duplicates.
export const regexEsc = (s) => String(s).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

/** The full generated/windowrules.lua from the rules list. */
export function windowRulesLuaText(rules) {
  let s = "-- AUTO-GENERATED by Settings → Window Rules. Do not edit by hand.\n";
  let n = 0;
  for (const r of rules || []) {
    const klass = String(r.class || "").trim();
    const ws = Math.trunc(Number(r.workspace)) || 0;
    const mode = r.mode === "float" || r.mode === "tile" ? r.mode : "";
    if (!klass || (ws <= 0 && !mode)) continue; // a rule with no effect is skipped, not an error
    n += 1;
    s += "hl.window_rule({\n";
    s += `    name  = "user-rule-${n}",\n`;
    s += `    match = { class = "^${luaEsc(regexEsc(klass))}$" },\n`;
    if (ws > 0) s += `    workspace = "${ws}",\n`;
    if (mode) s += `    ${mode} = true,\n`;
    s += "})\n";
  }
  return s;
}
