<script>
  import { onMount } from "svelte";
  import * as api from "../api.js";
  import { hypridleConfText, idlePolicyText } from "../hypr.js";
  import { prefs, errorMsg, flashApplied } from "../stores.js";
  import { setPrefs } from "../overrides.js";
  import Card from "./ui/Card.svelte";
  import ToggleRow from "./ui/ToggleRow.svelte";
  import SelectRow from "./ui/SelectRow.svelte";
  import SliderRow from "./ui/SliderRow.svelte";

  let hypridleOk = true;
  onMount(async () => {
    try {
      const d = await api.diagnostics();
      hypridleOk = d.hypridle !== "no";
    } catch {}
  });

  $: saver = {
    enabled: !!$prefs.saver?.enabled,
    min: Number($prefs.saver?.min ?? 5),
    style: $prefs.saver?.style || "clock",
    lock: !!$prefs.saver?.lock,
    lockAfterMin: Number($prefs.saver?.lockAfterMin ?? 5)
  };
  // The battery timeline is regenerated by the shell when power flips; from
  // here we generate the AC one — the shell rewrites it on the next transition.
  $: policy = idlePolicyText(saver, false);

  async function change(patch) {
    const next = { ...saver, ...patch };
    try {
      await setPrefs({ saver: { ...($prefs.saver || {}), ...next } });
      await api.writeConfig("hypr/generated/hypridle.conf", hypridleConfText(next, false));
      await api.restartHypridle();
      flashApplied();
    } catch (e) {
      errorMsg.set(String(e));
    }
  }
</script>

<div class="mx-auto max-w-3xl space-y-6 p-5 sm:p-8">
  <h1 class="text-lg font-semibold">Screensaver</h1>

  {#if !hypridleOk}
    <div class="card border-amber-400/40 p-4 text-xs text-amber-600 dark:text-amber-400">
      hypridle is not installed — the screensaver (and idle auto-lock) needs it:
      <code class="rounded bg-zinc-100 px-1 dark:bg-zinc-700">sudo pacman -S hypridle</code>
    </div>
  {/if}

  <Card>
    <ToggleRow
      title="Enable screensaver"
      sub="Covers every display after the idle timeout; any key, click or mouse move dismisses it."
      on={saver.enabled}
      toggled={() => change({ enabled: !saver.enabled })}
    />
    <SliderRow
      label="Idle timeout"
      value={saver.min}
      from={1}
      to={60}
      unit=" min"
      dim={!saver.enabled}
      moved={(v) => change({ min: Math.round(v) })}
    />
    <SelectRow
      label="Style"
      options={[
        { label: "Clock", value: "clock" },
        { label: "Blank (black)", value: "blank" }
      ]}
      value={saver.style}
      dim={!saver.enabled || saver.lock}
      picked={(v) => change({ style: v })}
    />
  </Card>

  <section>
    <div class="section-title">Locking</div>
    <Card>
      <ToggleRow
        title="Require password"
        sub="Idle goes straight to the session lock screen instead of the dismissable saver."
        dim={!saver.enabled}
        on={saver.lock}
        toggled={() => change({ lock: !saver.lock })}
      />
      <SelectRow
        label="Lock after the saver starts"
        options={[
          { label: "Never", value: 0 },
          { label: "1 min", value: 1 },
          { label: "5 min", value: 5 },
          { label: "10 min", value: 10 },
          { label: "15 min", value: 15 },
          { label: "30 min", value: 30 }
        ]}
        value={saver.lockAfterMin}
        dim={!saver.enabled || saver.lock}
        picked={(v) => change({ lockAfterMin: Number(v) })}
      />
    </Card>
  </section>

  <div class="flex items-center gap-3">
    <button
      class="btn-primary !py-1.5 text-xs"
      disabled={!saver.enabled}
      on:click={() => api.qsIpc("saver", "show").catch((e) => errorMsg.set(String(e)))}
    >
      Preview
    </button>
    <span class="text-xs text-zinc-400">Shows the saver now — any key dismisses it.</span>
  </div>

  <p class="text-xs text-zinc-400 dark:text-zinc-500">Current timeline: {policy}</p>
  <p class="text-xs text-zinc-400 dark:text-zinc-500">
    With the saver disabled the stock behaviour stays: auto-lock after 5 minutes idle.
    Idle-suspend on battery (15 min) is always kept, and every stage lands sooner on battery.
    Playing media, a fullscreen window, or the bar's Insomnia toggle keep all of this away.
    Timing is enforced by hypridle — settings apply immediately, no restart needed.
  </p>
</div>
