<script>
  import { onMount } from "svelte";
  import * as api from "../api.js";
  import { hypridleConfText, idlePolicyText } from "../hypr.js";
  import { prefs, errorMsg, flashApplied } from "../stores.js";
  import { setPrefs } from "../overrides.js";
  import ToggleRow from "./ui/ToggleRow.svelte";
  import SelectRow from "./ui/SelectRow.svelte";
  import SliderRow from "./ui/SliderRow.svelte";

  let hypridleOk = true;
  onMount(async () => {
    try {
      const d = await api.diagnostics();
      hypridleOk = d.hypridle !== "no";
    } catch {}
  });

  $: saver = {
    enabled: !!$prefs.saver?.enabled,
    min: Number($prefs.saver?.min ?? 5),
    style: $prefs.saver?.style || "clock",
    lock: !!$prefs.saver?.lock,
    lockAfterMin: Number($prefs.saver?.lockAfterMin ?? 5)
  };
  // The battery timeline is regenerated by the shell when power flips; from
  // here we generate the AC one — the shell rewrites it on the next transition.
  $: policy = idlePolicyText(saver, false);

  async function change(patch) {
    const next = { ...saver, ...patch };
    try {
      await setPrefs({ saver: { ...($prefs.saver || {}), ...next } });
      await api.writeConfig("hypr/generated/hypridle.conf", hypridleConfText(next, false));
      await api.restartHypridle();
      flashApplied();
    } catch (e) {
      errorMsg.set(String(e));
    }
  }
  import Page from "./ui/Page.svelte";
  import Group from "./ui/Group.svelte";
  import Row from "./ui/Row.svelte";
  import Alert from "./ui/Alert.svelte";
</script>

<Page title="Screensaver" desc="What the screens show when you step away, and when the session locks.">
  <svelte:fragment slot="actions">
    <button
      class="ewe-btn ewe-btn--secondary"
      disabled={!saver.enabled}
      title="Shows the screensaver now. Any key dismisses it."
      on:click={() => api.qsIpc("saver", "show").catch((e) => errorMsg.set(String(e)))}
    >
      Preview
    </button>
  </svelte:fragment>

  {#if !hypridleOk}
    <Alert tone="warning" title="hypridle isn't installed">
      The screensaver and automatic locking need it. Install it with <code>sudo pacman -S hypridle</code>.
    </Alert>
  {/if}

  <Group>
    <ToggleRow
      title="Screensaver"
      sub="Covers every display after the idle time. Any key, click or mouse move dismisses it."
      on={saver.enabled}
      toggled={() => change({ enabled: !saver.enabled })}
    />
    <SliderRow
      label="Start after"
      value={saver.min}
      from={1}
      to={60}
      unit=" min"
      dim={!saver.enabled}
      moved={(v) => change({ min: Math.round(v) })}
    />
    <SelectRow
      label="Style"
      options={[
        { label: "Clock", value: "clock" },
        { label: "Blank", value: "blank" }
      ]}
      value={saver.style}
      dim={!saver.enabled || saver.lock}
      picked={(v) => change({ style: v })}
    />
  </Group>

  <Group title="Locking">
    <ToggleRow
      title="Require password"
      sub="When you're idle, go straight to the lock screen instead of the screensaver."
      dim={!saver.enabled}
      on={saver.lock}
      toggled={() => change({ lock: !saver.lock })}
    />
    <SelectRow
      label="Lock after the screensaver starts"
      options={[
        { label: "Never", value: 0 },
        { label: "1 min", value: 1 },
        { label: "5 min", value: 5 },
        { label: "10 min", value: 10 },
        { label: "15 min", value: 15 },
        { label: "30 min", value: 30 }
      ]}
      value={saver.lockAfterMin}
      dim={!saver.enabled || saver.lock}
      picked={(v) => change({ lockAfterMin: Number(v) })}
    />
  </Group>

  <p class="note">Current timeline: {policy}</p>
  <p class="note">
    With the screensaver off, the desktop still locks after 5 minutes idle. On battery it suspends
    after 15 minutes, and every stage comes sooner. Playing media, a fullscreen window or keep awake
    in the bar hold all of this off. hypridle applies changes at once; no restart needed.
  </p>
</Page>
